### ISSUE TITLE
Undefined_endpoint

### ISSUE THREAD

**Issue by sos3443** [twitter/diffy#49]
i met a problem and that is when i run diffy i got response ,the URL is 192.168.1.85:31900/v2/products?category_id=kNylmZ and what i saw from the page is Undefined_endpoint.i don't know how to deal with it

![diffy1](https://cloud.githubusercontent.com/assets/19179375/19263397/bc73863a-8fce-11e6-9296-352e603c4039.jpg)

**Comment by puneetkhanduri** [comment]
Your test requests need to specify the endpoint name under which their results should be aggregated. This is done by setting the Canonical-Resource header to the endpoint name in all your inbound requests.

See the curl commands in this [example](https://github.com/twitter/diffy/tree/master/example).

**Comment by buzzdan** [comment]
@puneetkhanduri why is it mandatory ? is it possible to parse the endpoint name and use it ?
my production requests dont have this header and it could be nice if it would just work out of the box... WDYT ?

**Comment by puneetkhanduri** [comment]
Hi Dan. Your service probably has multiple endpoints. These endpoints may have path parameters like /users/:userid. This makes it impossible to group request urls into the same logical endpoint for analysis. If we don't group the endpoints, the UI becomes useless because each request may end up creating its own endpoint in the UI with a sample size of 1 rendering Diffy useless. In order to correctly group the traffic into the right logical endpoints, we require this header.

**Comment by buzzdan** [comment]
@puneetkhanduri thanks for the answer.
yes i'm aware of this problem, but whats the alternative? right now i'm throwing an nginx infront of diffy (kinda funny since diffy is a reverse proxy) that only parses the url and adds it as an header.
maybe it could be nice to be able to pass a url parsing regex as a parameter ?
your example `/users/:userid` is great since we would only want to capture `users` right?
