### ISSUE TITLE
how to process the difference of data?

### ISSUE THREAD

**Issue by sephirothgao** [twitter/diffy#84]
How to process the difference of data in different of server? 
Different server have different data. So the request sending to primary is working, but it may not work in secondary or candidate. They have different database.
How to fix this issue?

**Comment by puneetkhanduri** [comment]
This cannot be fixed with Diffy due to its fundamental architectural constraints. We had to build something completely different from the ground up to address this and other limitations we ran into with Diffy. Please checkout https://twitter.com/isotopeproject if you are interested in learning more.

**Comment by sephirothgao** [comment]
Thank you! I will learn about isotopeproject. But I can't reach twitter's domain. Can you commit the code to github?

**Comment by sephirothgao** [comment]
still can't access the goo.gl...
